from __future__ import annotations
from typing import Protocol

class CommanderControlPort(Protocol):
    def safe_pause(self): ...
    def enter_safe(self): ...
    def emergency_stop(self): ...
    def resume(self): ...
    def restart_service(self, service_name: str): ...
    def acknowledge_incident(self, incident_id: str): ...
