from __future__ import annotations
from typing import Protocol, Iterable
from uuid import UUID
from omega_memory.domain.models import MarketObservation, ObservationOutcome

class ObservationStoragePort(Protocol):
    def append_observation(self, observation: MarketObservation) -> None: ...
    def get_observation(self, observation_id: UUID) -> MarketObservation: ...
    def iter_observations(self, instrument_id: str) -> Iterable[MarketObservation]: ...

class OutcomeStoragePort(Protocol):
    def append_outcome(self, outcome: ObservationOutcome) -> None: ...
    def get_outcome(self, observation_id: UUID) -> ObservationOutcome | None: ...
