from __future__ import annotations
from typing import Protocol

class ProcessSupervisorPort(Protocol):
    def start(self, service_id: str): ...
    def stop(self, service_id: str): ...
    def restart(self, service_id: str): ...
    def status(self, service_id: str): ...
