from __future__ import annotations
from typing import Protocol
from omega_resilience.domain.models import ResourceSnapshot, NetworkSnapshot, ClockSnapshot

class SystemHealthPort(Protocol):
    def resources(self) -> ResourceSnapshot: ...
    def network(self, target: str) -> NetworkSnapshot: ...
    def clock(self) -> ClockSnapshot: ...
