plugins { id 'com.android.library' }
android {
    namespace 'omega.atlas.mobile.v2.testing.fakes'
    compileSdk 36
    defaultConfig { minSdk 26 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    api project(':core:model')
    api project(':core:result')
}
