RESEARCH_CAPABILITIES = {
    "READ_MARKET_MEMORY",
    "READ_WAIT_LEARNING",
    "READ_COUNTERFACTUAL",
    "READ_VALIDATION",
    "READ_LOGS",
    "WRITE_RESEARCH_NAMESPACE",
    "CREATE_CANDIDATE_PACKAGE",
    "SUBMIT_VALIDATION",
}

FORBIDDEN_CAPABILITIES = {
    "BROKER_WRITE",
    "LIVE_CONFIG_WRITE",
    "RISK_OVERRIDE",
    "SAFETY_OVERRIDE",
    "KILL_SWITCH_OVERRIDE",
    "CHAMPION_REPLACE",
    "MONEY_LEDGER_WRITE",
}

def capability_allowed(name: str) -> bool:
    return name in RESEARCH_CAPABILITIES and name not in FORBIDDEN_CAPABILITIES
