from __future__ import annotations
from typing import Protocol, Mapping, Any

class ResearchAIPort(Protocol):
    def classify_log(self, text: str) -> Mapping[str, Any]: ...
    def draft_hypothesis(self, evidence: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def summarize_validation(self, report: Mapping[str, Any]) -> Mapping[str, Any]: ...
