from __future__ import annotations
from typing import Protocol, Iterable, Mapping, Any

class ResearchDataPort(Protocol):
    def query_wait_statistics(self, instrument_id: str) -> Iterable[Mapping[str,Any]]: ...
    def query_trade_analytics(self, strategy_id: str) -> Iterable[Mapping[str,Any]]: ...
    def query_blackbox_incidents(self) -> Iterable[Mapping[str,Any]]: ...
